name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: helloooo
      id: helloooo
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: helloooo
        setup-command: ''
        command: ls
        input: hi wow
        expected-output: wow
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLOOOO_RESULTS: "${{steps.helloooo.outputs.result}}"
      with:
        runners: helloooo
